require: rubocop-rspec

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*
