require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*
